### ISSUE TITLE
Add Currency option (or ability to remove the $ sign)

### ISSUE THREAD

**Issue by justbest23** [custom-cards/upcoming-media-card#102]
It would be nice to be able to replace the default $ with something else to match whatever currency I'm used to. For example, this would be in ZAR: 
![image](https://github.com/user-attachments/assets/ac69655c-8795-4124-9115-088cd7995525)

It would also be nice to be able to change the font size so that more things could fit on the screenshot!

**Comment by mkanet** [comment]
Hi @justbest23 in order to provide currency support for your country, the Integration generating the data needs to be updated.  In the above case, you would need to submit a feature enhancement to the Stream Wishlist integration.  The person who created the Steam Wishlist integration is friendly and would probably do this for you if you ask nicely. :-)

Although, Upcoming Media Card allows for changing text size for any line, I agree it is still not enough room for certain integrations.  Making the font even smaller would be a bit too small.  I think the correct way to do this is to add a enhancement to increase the general width of the fanart/poster cards.  As soon as I get time to add this enhancement, I will let you know.

**Comment by justbest23** [comment]
Thanks for the response!
Regarding the currency stuff, it's been brought up as an issue on the Boralyl repo as seen here: (https://github.com/boralyl/steam-wishlist/issues/27#issue-comment-box)

I'm not sure if maybe it actually is on his side or of its on your side?

To be clear, the number in the Steam wishlist item is actually the correct ZAR number, not USD. But it's the existence of the $ sign that's the issue here.



I agree that adding an option to make the poster cards wider would be a great fix for this! Regrading changing text sizes, I don't think I saw that in the docs? Unless I'm just wrong haha.

**Comment by mkanet** [comment]
The integration is what determines what is displayed in the card.  Upcoming Media Card just displays the existing text on each line that the integration provides.  The Steam Wishlist integration will need to check your home assistant configuration for what region you live in/timezone; then, automatically calculate and convert the amount of money to local currency.  I am not sure if the repository owner/manager would be motivated to do this.  I wish I had more time, I would do this myself.  In fact, it was my PR for the Steam Wishlist repo that provided the latest support for Upcoming Media Card.  First, lets see what he responds with, if anything.  If I get some free time , I will submit a PR for this.

**Comment by mkanet** [comment]
> Thanks for the response! Regarding the currency stuff, it's been brought up as an issue on the Boralyl repo as seen here: ([boralyl/steam-wishlist#27 (comment)](https://github.com/boralyl/steam-wishlist/issues/27#issue-comment-box))
> 
> I'm not sure if maybe it actually is on his side or of its on your side?
> 
> To be clear, the number in the Steam wishlist item is actually the correct ZAR number, not USD. But it's the existence of the $ sign that's the issue here.
> 
> I agree that adding an option to make the poster cards wider would be a great fix for this! Regrading changing text sizes, I don't think I saw that in the docs? Unless I'm just wrong haha.

Please don't forget to post here if you hear back from @boralyl.  If you don't hear him in a while, post here anyway, I may have free time in the future to add this to the Steam Wishlist integration.

**Comment by boralyl** [comment]
When I looked into the [original issue](https://github.com/boralyl/steam-wishlist/issues/27) I concluded that the json that is being parsed doesn't tell you what the currency is.  It defaults to what the user has configured in steam.  I had forgotten that we had hardcoded some data in the extra state attributes.  So that's where the `$` is coming from: https://github.com/boralyl/steam-wishlist/blob/main/custom_components/steam_wishlist/util.py#L58

If you want to try to use HA's configured currency, I might suggest that instead of relying on a hardcoded-formatted value from the integration that the price info is formatted by the the card instead.  You can access the user's configured currency via `hass.config.currency` in the card JS.  The sale price can be calculated from the `normal_price` and `percent_off` keys of the json data.

**Comment by mkanet** [comment]
> When I looked into the [original issue](https://github.com/boralyl/steam-wishlist/issues/27) I concluded that the json that is being parsed doesn't tell you what the currency is. It defaults to what the user has configured in steam. I had forgotten that we had hardcoded some data in the extra state attributes. So that's where the `$` is coming from: https://github.com/boralyl/steam-wishlist/blob/main/custom_components/steam_wishlist/util.py#L58
> 
> If you want to try to use HA's configured currency, I might suggest that instead of relying on a hardcoded-formatted value from the integration that the price info is formatted by the the card instead. You can access the user's configured currency via `hass.config.currency` in the card JS. The sale price can be calculated from the `normal_price` and `percent_off` keys of the json data.

Hey @boralyl! Thanks for the tip.  Sounds feasible.  Not sure if Ill be motivated to do it; given my limited spare time.

**Comment by boralyl** [comment]
Steam recently removed the endpoint that was being used to get wish list data. Now that I am using their store api, you can now specify a country and it returns the currency formatted based on that country.  So after upgrading to [v3.0.0](https://github.com/boralyl/steam-wishlist/releases/tag/v3.0.0), the currency will match the country configured in HA.

**Comment by mkanet** [comment]
Good to know.

**Comment by justbest23** [comment]
Thanks for the update!
