### ISSUE TITLE
Displayed without boxart

### ISSUE THREAD

**Issue by chris8837** [custom-cards/upcoming-media-card#40]
## Describe the bug:

Chrome and cleared cache, works on all my devices but not chrome on a desktop.  works with edge though...
## Config YAML:

entity: sensor.sonarr_upcoming_media
title: Upcoming TV
type: 'custom:upcoming-media-card'
## Components:

Sonarr component
## HA Error:

No error
## Troubleshooting Guide:

Yes tried it all
## Home Assistant Version:

Latest
## Screenshots:

No boxart
![Capture](https://user-images.githubusercontent.com/42333632/69600433-74286600-0fc5-11ea-9069-c36f2bbf7ed2.PNG)

**Comment by BrettWa** [comment]
See here: https://github.com/custom-components/sensor.sonarr_upcoming_media/issues/12

**Comment by maykar** [comment]
Images URLs for the Sonarr component have been fixed in it's latest release. If you're still having issues it's probably related to http/https issues. You can see if this is the issue by pressing F12 and seeing this error in your dev console `ERR_BLOCKED_BY_CLIENT`.

You could access your HA using a remote URL with https, add a cert for https to HA, or the only other fix for this would be for me to rewrite this integration to download images like the Plex component does. Right now I've got my hands full with the rewrite of Compact Custom Header and some other things, but this is on my list.

**Comment by BrettWa** [comment]
Updated on myside, still had the issue - out of boredom, I googled the error (ERR_BLOCKED_BY_CLIENT) to understand it better... turns out my ad blocker was the culprit, white listed my URL and all good now.

**Comment by maykar** [comment]
Genius, thank you. I was assuming it was http/https issues, but on my side as well it was my adblocker. I'll add something to the readme about it when I get the chance, thank you.

I think this one can be closed.
