### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by yfands** [custom-cards/upcoming-media-card#74]
First, awesome card, nice job.

iam using kodi.
My 'problem' is that my TV show list is too long ;-)
I follow different series some have over 20 episodes, so a long list.
What I like to see is an option to group TV series, so show only one instance of the series and not all 20+ episodes.
The text can consist of Name of the series, number of episodes, year.

Regards
Frank

**Comment by bugs181** [comment]
Came here to request this very feature.

**Comment by mkanet** [comment]
@yfands @bugs181 Done!

**Comment by mkanet** [comment]
@loryanstrant and @bugs181 This actually has to be done by the integration you are using (for example:  https://github.com/custom-components/sensor.kodi_recently_added).  It isn't something Upcoming Media Card can do since Upcoming Media Card only displays what each sensor has to offer "as is".  Upcoming Media Card can only sort the existing items, that's it.  It can't manipulate/consolidate the data in an existing sensor.

For example, if you are using the Kodi Integration for upcoming Media card, it would need, for example, a new sensor called  `sensor.kodi_TV_series`; where each item in the sensor has the following data: Name of the series, number of episodes, year, premiere, etc.  Then, Upcoming Media Card will display whatever is in the sensor."as is".  

I think Emby Upcoming Media integration for upcoming media card has a sensor that does something like this.  You would have to make a feature request for the integration you are using to create a new sensor that provides this data the way you want to see it in upcoming media card.  It can't be changed after the sensor provides the data to Upcoming Media Card.
